---
title: "w11l2_act.qmd"
author: "Eliel"
format: html
---

```{r}
library(mlbench)
library(tidyverse)
data(BostonHousing2)

```

```{r}
meanVal = c()
for (item in names(BostonHousing2)){
  meanVal <- c(meanVal, sum(BostonHousing2[[item]]) / length(BostonHousing2[[item]]))
}
```

```{r}
outliers <- function(Var,probs = c(0.25, 0.75)) {
 #Step 1: Find Q1, Q3, and the IQR
quarts <- quantile(BostonHousing2[[Var]], probs = probs)
iqr <- quarts[2] - quarts[1]

# Step 2: Find the bounds
ub <- quarts[2] + 1.5 * iqr
lb <- quarts[1] - 1.5 * iqr

# Step 3: Show the outliers
inds <- which(BostonHousing2[[Var]] < lb | BostonHousing2[[Var]] > ub)
BostonHousing2 |> slice(inds) |>  head(3)
 return() 
}
outliers ("medv", c(0.3,0.8))
```

```{r}
BHsmall <- BostonHousing2 |> 
  select(medv, crim, nox, indus) |>
  slice(1:5)
```


```{r}
for(item in BHsmall){
 outlier(item)
}
```

```{r}
BHsmall|>
  map_dbl(mean)
```

```{r}
subtractv <- function(x, y){
  x - y
}
map2(BHsmall$medv, BHsmall$indus, subtractv)
```

