---
title: "Activities from Week 10, Lecture 1: Data Ethics"
subtitle: "SDS 192: Introduction to Data Science"
author: "YOUR NAME HERE"
---

## Introduction

We've discussed some ideas regarding data ethics. With those around you, you will discuss your thoughts on the video and answer questions regarding two different articles.

## Carissa Véliz: How privacy can save your life

You've just watched a TEDTalk from Carissa Véliz about how data privacy should be used to protect your livelihood. You can access the video for reference [here](https://www.youtube.com/watch?v=xSPRouBvgFE).

After talking to others about the video, answer the following questions below:

::: {.callout-important}
###### Q1

What are some important ideas that Carissa Véliz talked about in the video? What are your thoughts to some of the examples she used and her perspective?
#Carissa discussed the aspect of data privacy being an important ting that mnay people are unaware of. Starting since the 1900s she gave examples of how data banks could be used for crimes and how this banks come in the forms of technology that people use now and do not know that their data can be leaked. This was spreading awareness but I end up with the question of how to balance between using technology and trying to protect your data.
:::

## Your data is diminishing your freedom

Read the New York Times article "Your Data is Diminishing Your Freedom" at the following link [here](https://www.nytimes.com/interactive/2023/03/20/magazine/colin-koopman-interview.html). After discussing your thoughts on the piece, answer the following questions:

::: {.callout-important}
###### Q2

What does it mean that "we have become our own data?" How does that sentiment affect your personal decision-making, and how we define ourselves?
#This was thought provoking to me and made me start to analyse if I had physical personal documents in a folder because I definitely have them online. It also made me ponder over my interactions over the internet. I felt guilty  because I realised I have so much information saved uo on the net that I may only be my body indeed.
:::

::: {.callout-important}
###### Q3

Using the article as support, what are some concerns you personally have about the use of your data? 

#Are there appropriate resources to protect data online and is misinterpretation of data a punishable crime by law?


:::

## Federal Data Strategy

The U.S. Government has a Federal Data Strategy with the hopes of defining how to use data to serve the public and steward resources while "protecting security, privacy, and confidentiality."

You will read page 4 of the Data Ethics Framework based on the strategy [here](https://resources.data.gov/assets/documents/fds-data-ethics-framework.pdf). After discussing your thoughts on the piece, answer the following questions:


::: {.callout-important}
###### Q4

Discuss examples about how a government (or smaller body) could execute a data ethics tenet of your choice.
#I think a good example of a data ethic tenet should be laws put in place so that people become aware about the consequences of handling data unethically and principles for good data handling should be put in place as we have today.
:::

## Turn-in

Save the .qmd file inside your activities repository. Please stage, commit, and push to GitHub.